version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: deukuway-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - deukuway-network

  # PgAdmin (PostgreSQL management tool) - Optional
  pgadmin:
    image: dpage/pgadmin4
    container_name: deukuway-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - deukuway-network


  # Seq (for centralized logging) - Optional but useful for viewing Serilog logs
  seq:
    image: datalust/seq
    container_name: deukuway-seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - deukuway-network

volumes:
  postgres-data:
  pgadmin-data:
  seq-data:

networks:
  deukuway-network:
    driver: bridge